name: I need help
description: Create an issue to get support
labels: help
assignees:
  - Maxpro131
body:
  - type: textarea
    attributes:
      label: What's the problem?
      placeholder: |
        Enter your description here
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Post Requisites
      options:
        - label: I read all steps carefully, but I still need help
          required: true
